abuelitos/abuelitos/urls.py
from django.conf import settings
from django.conf.urls import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("civilizations.urls")),
]

if settings.DEBUG:
    urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

abuelitos/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("profile/logout/", views.logout_confirm_view, name="logout_confirm"),
    path("password_change/", views.password_change_view, name="password_change"),
    path("password_reset/", views.password_reset_view, name="password_reset"),
    path(
        "password_reset/done/",
        views.password_reset_done_view,
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.password_reset_confirm_view,
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.password_reset_complete_view,
        name="password_reset_complete",
    ),
    path("profile/", views.profile_view, name="profile"),
]

abuelitos/accounts/models.py
import uuid

from django.contrib.auth import models as auth_models
from django.db import models
from django.urls import reverse_lazy


class User(auth_models.AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    def get_absolute_url(self):
        return reverse_lazy("accounts:profile")

abuelitos/accounts/views.py
from django.contrib import auth
from django.contrib.auth import views as views_auth
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views import generic as views_generic


class LoginView(views_auth.LoginView):
    template_name = "accounts/login.html"


login_view = LoginView.as_view()


class LogoutConfirmView(views_generic.TemplateView):
    template_name = "accounts/profile_logout_confirm.html"


logout_confirm_view = LogoutConfirmView.as_view()


class LogoutView(views_auth.LogoutView):
    template_name = "accounts/logged_out.html"


logout_view = LogoutView.as_view()


class PasswordChangeView(SuccessMessageMixin, views_auth.PasswordChangeView):
    template_name = "accounts/profile_password_change_form.html"
    success_message = _("Your password was updated successfully.")
    success_url = reverse_lazy("accounts:password_change")


password_change_view = PasswordChangeView.as_view()


class PasswordResetView(views_auth.PasswordResetView):
    template_name = "accounts/password_reset_form.html"


password_reset_view = PasswordResetView.as_view()


class PasswordResetDoneView(views_auth.PasswordResetDoneView):
    template_name = "accounts/password_reset_done.html"


password_reset_done_view = PasswordResetDoneView.as_view()


class PasswordResetConfirmView(views_auth.PasswordResetConfirmView):
    template_name = "accounts/password_reset_confirm.html"


password_reset_confirm_view = PasswordResetConfirmView.as_view()


class PasswordResetCompleteView(views_auth.PasswordResetCompleteView):
    template_name = "accounts/password_reset_complete.html"


password_reset_complete_view = PasswordResetCompleteView.as_view()


class ProfileView(SuccessMessageMixin, views_generic.UpdateView):
    template_name = "accounts/profile_my_information.html"
    model = auth.get_user_model()
    fields = [
        "username",
        "first_name",
        "last_name",
    ]
    success_message = _("Your profile was updated successfully.")

    def get_object(self, queryset=None):
        return self.get_queryset().get(pk=self.request.user.pk)


profile_view = ProfileView.as_view()

abuelitos/accounts/templates/accounts/login.html
{% extends "th_olian/base.html" %}
{% load i18n static %}
{% block content %}
    <!-- Start Containerbar -->
    <div id="containerbar" class="containerbar authenticate-bg">
        <!-- Start Container -->
        <div class="container">
            <div class="auth-box login-box">
                <!-- Start row -->
                <div class="row no-gutters align-items-center justify-content-center">
                    <!-- Start col -->
                    <div class="col-md-6 col-lg-5">
                        <!-- Start Auth Box -->
                        <div class="auth-box-right">
                            <div class="card">
                                <div class="card-body">
                                    <form method="post" action="{% url "accounts:login" %}">
                                        {% csrf_token %}
                                        <div class="form-head">
                                            <a href="index.html" class="logo"><img src="{% static "th_olian/images/logo.svg" %}" class="img-fluid" alt="logo"></a>
                                        </div>
                                        <h4 class="text-primary my-4">{% translate "Log in!" %}</h4>
                                        {% if next %}
                                            {% if user.is_authenticated %}
                                            <div class="alert alert-danger" role="alert">{% translate "Your account doesn't have access to this page. To proceed, please login with an account that has access." %}</div>
                                            {% else %}
                                            <div class="alert alert-danger" role="alert">{% translate "Please login to see this page." %}</div>
                                            {% endif %}
                                        {% endif %}
                                        {% if form.errors %}
                                        <div class="alert alert-danger" role="alert">{% translate "Your username and password didn't match. Please try again." %}</div>
                                        {% endif %}
                                        <div class="form-group">
                                            <input type="text" class="form-control" id="{{ form.username.id_for_label }}" name="{{ form.username.html_name }}" placeholder="{% translate "Username" %}" required>
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control" id="{{ form.password.id_for_label }}" name="{{ form.password.html_name }}" placeholder="{% translate "Password" %}" required>
                                        </div>
                                        <div class="form-row mb-3">
                                            <div class="col">
                                              <div class="forgot-psw"> 
                                                  <a id="forgot-psw" href="{% url "accounts:password_reset" %}" class="font-14">{% translate "Forgot password?" %}</a>
                                              </div>
                                            </div>
                                        </div>                          
                                        <button type="submit" class="btn btn-success btn-lg btn-block font-18">{% translate "Log in" %}</button>
                                        <input type="hidden" name="next" value="{{ next }}">
                                    </form>
                                    <div class="login-or">
                                        <h6 class="text-muted">{% translate "OR" %}</h6>
                                    </div>
                                    <p class="mb-0 mt-3">{% translate "Don't have a account?" %} <a href="user-register.html">{% translate "Sign up" %}</a></p>
                                </div>
                            </div>
                        </div>
                        <!-- End Auth Box -->
                    </div>
                    <!-- End col -->
                </div>
                <!-- End row -->
            </div>
        </div>
        <!-- End Container -->
    </div>
    <!-- End Containerbar -->
{% endblock content %}

abuelitos/accounts/templates/accounts/profile_base.html
{% extends "th_olian/dashboard_base.html" %}
{% load i18n static %}

{% block breadcrumbbar_list %}
<li class="breadcrumb-item"><a href="{% url "accounts:profile" %}">{% translate "My Profile" %}</a></li>
{% endblock breadcrumbbar_list %}

{% block contentbar_content %}
<!-- Start row -->
<div class="row">
    <!-- Start col -->
    <div class="col-lg-5 col-xl-3">
        <div class="card m-b-30">
            <div class="card-header">                                
                <h5 class="card-title mb-0">{% translate "My Profile" %}</h5>
            </div>
            <div class="card-body">
                <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                    <a class="nav-link mb-2 {% block active_section_my_information %}{% endblock active_section_my_information %}" href="{% url "accounts:profile" %}" role="tab" aria-controls="v-pills-dashboard" aria-selected="true"><i class="ri-user-line mr-2"></i>{% translate "My Information" %}</a>
                    <a class="nav-link mb-2 {% block active_section_password_change %}{% endblock active_section_password_change%}" href="{% url "accounts:password_change" %}" role="tab" aria-controls="v-pills-order" aria-selected="false"><i class="ri-key-line mr-2"></i>{% translate "Change Password" %}</a>
                    <a class="nav-link text-danger {% block active_section_logout %}{% endblock active_section_logout %}" href="{% url "accounts:logout_confirm" %}" role="tab" aria-controls="v-pills-logout" aria-selected="false"><i class="ri-shut-down-line mr-2"></i>{% translate "Log Out" %}</a>
                </div>
            </div>
        </div>
    </div>
    <!-- End col -->
    <!-- Start col -->
    <div class="col-lg-7 col-xl-9">
        <div class="tab-content" id="v-pills-tabContent">{% block tab_content %}{% endblock tab_content %}</div>                        
    </div>
    <!-- End col -->
</div>
<!-- End row -->
{% endblock contentbar_content %}

abuelitos/accounts/templates/accounts/profile_logout_confirm.html
{% extends "accounts/profile_base.html" %}
{% load i18n static %}

{% block active_section_logout %}active{% endblock active_section_logout %}

{% block breadcrumbbar_title %}{% translate "Log Out" %}{% endblock breadcrumbbar_title %}

{% block breadcrumbbar_list %}
{{ block.super }}
<li class="breadcrumb-item active" aria-current="page">{% translate "Log Out" %}</li>
{% endblock breadcrumbbar_list %}

{% block tab_content %}

<!-- My Logout Start -->
<div class="tab-pane active" id="v-pills-logout" role="tabpanel" aria-labelledby="v-pills-logout-tab">
    <div class="card m-b-30">
        <div class="card-header">                                
            <h5 class="card-title mb-0">{% translate "Log Out" %}</h5>                                       
        </div>
        <div class="card-body">
            <div class="row justify-content-center">
                <div class="col-lg-6 col-xl-4">
                    <div class="logout-content text-center my-5">
                        <img src="{% static "th_olian/images/ecommerce/logout.svg" %}" class="img-fluid mb-5" alt="logout">
                        <h2 class="text-success">{% translate "Log Out?" %}</h2>
                        <p class="my-4">{% translate "Are you sure to want to log out?" %}</p>
                        <div class="button-list">
                            <form method="post" action="{% url "accounts:logout" %}">
                            {% csrf_token %}
                                <button type="submit" class="btn btn-danger font-16"><i class="ri-check-line mr-2"></i>{% translate "Yes, I'm sure" %}</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- My Logout End -->

{% endblock tab_content %}

abuelitos/accounts/templates/accounts/profile_my_information.html
{% extends "accounts/profile_base.html" %}
{% load i18n static %}

{% block active_section_my_information %}active{% endblock active_section_my_information %}

{% block breadcrumbbar_title %}{% translate "My Information" %}{% endblock breadcrumbbar_title %}

{% block breadcrumbbar_list %}
{{ block.super }}
<li class="breadcrumb-item active" aria-current="page">{% translate "My Information" %}</li>
{% endblock breadcrumbbar_list %}

{% block tab_content %}
<!-- My Profile Start -->
<div class="tab-pane active" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab"> 
    <div class="card m-b-30">
        <div class="card-header">                                
            <h5 class="card-title mb-0">{% translate "My Information" %}</h5>
        </div>
        <div class="card-body">
            <form method="post" action="{% url "accounts:profile" %}">
                {% csrf_token %}
                {% if form.non_field_errors %}<div class="alert alert-danger" role="alert">{{ form.non_field_errors }}</div>{% endif %}
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="{{ form.username.id_for_label }}">{% translate "Username" %}</label>
                        <input type="text" class="form-control {{ form.username.errors|yesno:"is-invalid," }}" value="{{ form.username.initial }}" id="{{ form.username.id_for_label }}" name="{{ form.username.html_name }}">
                        <div class="invalid-feedback">{% for error in form.username.errors %}<li>{{ error|escape }}</li>{% endfor %}</div>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="email">{% translate "Email" %}</label>
                        <input type="email" class="form-control" value="{{ user.email }}" id="email" disabled>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="{{ form.first_name.id_for_label }}">{% translate "First Name" %}</label>
                        <input type="text" class="form-control {{ form.first_name.errors|yesno:"is-invalid," }}" value="{{ form.first_name.initial }}" id="{{ form.first_name.id_for_label }}" name="{{ form.first_name.html_name }}">
                        <div class="invalid-feedback">{% for error in form.first_name.errors %}<li>{{ error|escape }}</li>{% endfor %}</div>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="{{ form.last_name.id_for_label }}">{% translate "Last Name" %}</label>
                        <input type="text" class="form-control {{ form.last_name.errors|yesno:"is-invalid," }}" value="{{ form.last_name.initial }}" id="{{ form.last_name.id_for_label }}" name="{{ form.last_name.html_name }}">
                        <div class="invalid-feedback">{% for error in form.last_name.errors %}<li>{{ error|escape }}</li>{% endfor %}</div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="last_login">{% translate "Last Time Logged In" %}</label>
                        <input type="text" class="form-control" value="{{ user.last_login }}" id="last_login" disabled>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="date_joined">{% translate "Date Joined" %}</label>
                        <input type="text" class="form-control" value="{{ user.date_joined }}" id="date_joined" disabled>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary-rgba font-16"><i class="ri-save-line mr-2"></i>{% translate "Update My Information" %}</button>
            </form>
        </div>
    </div>
</div>
<!-- My Profile End -->
{% endblock tab_content %}

abuelitos/accounts/templates/accounts/profile_password_change_form.html
{% extends "accounts/profile_base.html" %}
{% load i18n static %}

{% block active_section_password_change %}active{% endblock active_section_password_change %}

{% block breadcrumbbar_title %}{% translate "Change Password" %}{% endblock breadcrumbbar_title %}

{% block breadcrumbbar_list %}
{{ block.super }}
<li class="breadcrumb-item active" aria-current="page">{% translate "Change Password" %}</li>
{% endblock breadcrumbbar_list %}

{% block tab_content %}

<!-- My Profile Start -->
<div class="tab-pane active" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab"> 
    <div class="card m-b-30">
        <div class="card-header">                                
            <h5 class="card-title mb-0">{% translate "Change Password" %}</h5>
        </div>
        <div class="card-body">
            <form method="post" action="{% url "accounts:password_change" %}">
                {% csrf_token %}
                {% if form.non_field_errors %}<div class="alert alert-danger" role="alert">{{ form.non_field_errors }}</div>{% endif %}
                <div class="form-group row col-md-6">
                    <label for="{{ form.old_password.id_for_label }}">{% translate "Old Password" %}</label>
                    <input type="password" class="form-control {% if form.old_password.errors %}is-invalid{% endif %}" id="{{ form.old_password.id_for_label }}" name="{{ form.old_password.html_name }}">
                    <div class="invalid-feedback">{% for error in form.old_password.errors %}<li>{{ error|escape }}</li>{% endfor %}</div>
                </div>
                <div class="form-group row col-md-6">
                    <label for="{{ form.new_password1.id_for_label }}">{% translate "New Password" %}</label>
                    <input type="password" class="form-control {% if form.new_password1.errors %}is-invalid{% endif %}" id="{{ form.new_password1.id_for_label }}" name="{{ form.new_password1.html_name }}">
                    <div class="invalid-feedback">{% for error in form.new_password1.errors %}<li>{{ error|escape }}</li>{% endfor %}</div>
                </div>
                <div class="form-group row col-md-6">
                    <label for="{{ form.new_password2.id_for_label }}">{% translate "New Password Confirmation" %}</label>
                    <input type="password" class="form-control {% if form.new_password2.errors %}is-invalid{% endif %}" id="{{ form.new_password2.id_for_label }}" name="{{ form.new_password2.html_name }}">
                    <div class="invalid-feedback">{% for error in form.new_password2.errors %}<li>{{ error|escape }}</li>{% endfor %}</div>
                </div>
                <button type="submit" class="btn btn-primary-rgba font-16"><i class="ri-save-line mr-2"></i>{% translate "Change My Password" %}</button>
            </form>
        </div>
    </div>
</div>
<!-- My Profile End -->

{% endblock tab_content %}