abuelitos/abuelitos/urls.py
from django.conf import settings
from django.conf.urls import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("civilizations.urls")),
]

if settings.DEBUG:
    urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

abuelitos/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("profile/logout/", views.logout_confirm_view, name="logout_confirm"),
    path("password_change/", views.password_change_view, name="password_change"),
    path("password_reset/", views.password_reset_view, name="password_reset"),
    path(
        "password_reset/done/",
        views.password_reset_done_view,
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.password_reset_confirm_view,
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.password_reset_complete_view,
        name="password_reset_complete",
    ),
    path("profile/", views.profile_view, name="profile"),
]

abuelitos/civilizations/urls.py
from django.urls import path

from . import views

app_name = "civilizations"

urlpatterns = [
    path("", views.person_search_view, name="person_search"),
    path(
        "options_for_agem_code/",
        views.options_for_agem_code_view,
        name="options_for_agem_code",
    ),
    path(
        "options_for_loc_code/",
        views.options_for_loc_code_view,
        name="options_for_loc_code",
    ),
    path("<slug:slug>/", views.person_detail_view, name="person_detail"),
]

abuelitos/civilizations/forms.py
import datetime

from django import forms
from django.conf import settings
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from . import choices


class PersonSearchForm(forms.Form):
    full_name_or_alias = forms.CharField(
        required=False,
        max_length=200,
        min_length=1,
    )
    year_of_birth = forms.IntegerField(
        required=False,
        min_value=1,
    )
    year_of_death = forms.IntegerField(
        required=False,
        min_value=1,
    )
    agee_code = forms.ChoiceField(
        required=False,
        choices=choices.AGEECode.choices,
    )
    agem_code = forms.CharField(
        required=False,
        max_length=3,
    )
    loc_code = forms.CharField(
        required=False,
        max_length=4,
    )

    def clean_year_of_birth(self):
        year_of_birth = self.cleaned_data["year_of_birth"]
        if year_of_birth is None:
            return year_of_birth
        tzinfo = timezone.get_current_timezone() if settings.USE_TZ else None
        current_year = datetime.datetime.now(tz=tzinfo).year
        if year_of_birth > current_year:
            raise ValidationError(
                _(
                    "The year of birth cannot be later than %(current_year)s."
                    % {"current_year": current_year}
                )
            )
        return year_of_birth

    def clean_year_of_death(self):
        year_of_death = self.cleaned_data["year_of_death"]
        if year_of_death is None:
            return year_of_death
        tzinfo = timezone.get_current_timezone() if settings.USE_TZ else None
        current_year = datetime.datetime.now(tz=tzinfo).year
        if year_of_death > current_year:
            raise ValidationError(
                _(
                    "The year of death cannot be later than %(current_year)s."
                    % {"current_year": current_year}
                )
            )
        return year_of_death

    def clean(self):
        cleaned_data = super().clean()
        year_of_birth = cleaned_data.get("year_of_birth")
        year_of_death = cleaned_data.get("year_of_death")
        if year_of_birth and year_of_death:
            if year_of_birth > year_of_death:
                self.add_error(
                    "year_of_death",
                    _("The year of death cannot be earlier than the year of birth."),
                )
        return cleaned_data

abuelitos/civilizations/views.py
import datetime

from django.db.models import Q
from django.views import generic as views_generic

from . import choices, forms, models


class HomeView(views_generic.TemplateView):
    template_name = "th_olian/base.html"


home_view = HomeView.as_view()


class PersonSearchView(views_generic.ListView):
    template_name = "civilizations/person_search_form.html"
    model = models.Person
    paginate_by = 100

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = forms.PersonSearchForm(self.request.GET)
        context["options_for_agee_code"] = []
        context["options_for_agem_code"] = []
        context["options_for_loc_code"] = []
        agee_code = self.request.GET.get("agee_code")
        if agee_code in choices.AGEECode:
            context["options_for_agee_code"] = [
                {
                    "agee_code": state.value,
                    "agee_name": state.label,
                    "is_selected": state.value == agee_code,
                }
                for state in choices.AGEECode
            ]
            context["options_for_agem_code"] = (
                models.Locality.objects.get_municipalities_of_state(agee_code)
            )
            if agem_code := self.request.GET.get("agem_code"):
                for m in context["options_for_agem_code"]:
                    m["is_selected"] = m["agem_code"] == agem_code
                context["options_for_loc_code"] = (
                    models.Locality.objects.get_localities_of_municipality(
                        agee_code, agem_code
                    )
                )
                if loc_code := self.request.GET.get("loc_code"):
                    for l in context["options_for_loc_code"]:
                        l["is_selected"] = l["loc_code"] == loc_code
        return context

    def get_queryset(self):
        queryset = models.Person.objects.all()
        form = forms.PersonSearchForm(self.request.GET)
        if not form.is_valid():
            return queryset
        if full_name_or_alias := form.cleaned_data["full_name_or_alias"]:
            queryset = queryset.filter(
                Q(full_name__icontains=full_name_or_alias)
                | Q(alias__icontains=full_name_or_alias)
            )
        year_of_birth = form.cleaned_data["year_of_birth"]
        if year_of_birth is not None:
            date_start = (
                datetime.date(year_of_birth - 5, 1, 1)
                if year_of_birth >= 5
                else datetime.date(1, 1, 1)
            )
            date_end = datetime.date(year_of_birth + 5, 12, 31)
            queryset = queryset.filter(date_of_birth__range=(date_start, date_end))
        year_of_death = form.cleaned_data["year_of_death"]
        if year_of_death is not None:
            date_start = (
                datetime.date(year_of_death - 5, 1, 1)
                if year_of_death >= 5
                else datetime.date(1, 1, 1)
            )
            date_end = datetime.date(year_of_death + 5, 12, 31)
            queryset = queryset.filter(date_of_death__range=(date_start, date_end))
        if agee_code := form.cleaned_data["agee_code"]:
            queryset = queryset.filter(locality__agee_code=agee_code)
        if agem_code := form.cleaned_data["agem_code"]:
            queryset = queryset.filter(locality__agem_code=agem_code)
        if loc_code := form.cleaned_data["loc_code"]:
            queryset = queryset.filter(locality__loc_code=loc_code)
        return queryset


person_search_view = PersonSearchView.as_view()


class OptionsForAGEMCodeView(views_generic.TemplateView):
    template_name = "civilizations/options_for_agem_code.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        agee_code = self.request.GET.get("agee_code")
        context["localities"] = []
        if agee_code in choices.AGEECode:
            context["localities"] = models.Locality.objects.get_municipalities_of_state(
                agee_code
            )
        return context


options_for_agem_code_view = OptionsForAGEMCodeView.as_view()


class OptionsForLocCodeView(views_generic.TemplateView):
    template_name = "civilizations/options_for_loc_code.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        agee_code = self.request.GET.get("agee_code")
        agem_code = self.request.GET.get("agem_code")
        context["localities"] = models.Locality.objects.get_localities_of_municipality(
            agee_code, agem_code
        )
        return context


options_for_loc_code_view = OptionsForLocCodeView.as_view()


class PersonDetailView(views_generic.DetailView):
    template_name = "civilizations/person_detail.html"
    model = models.Person
    slug_field = "slug"
    slug_url_kwarg = "slug"


person_detail_view = PersonDetailView.as_view()

abuelitos/civilizations/templates/civilizations/options_for_agem_code.html
{% load i18n %}
<option value="" selected>{% translate "All Municipalities" %}</option>
{% for l in localities %}
<option value="{{ l.agem_code }}">{{ l.agem_name }}</option>
{% endfor %}

abuelitos/civilizations/templates/civilizations/options_for_loc_code.html
{% load i18n %}
<option value="" selected>{% translate "All Localities" %}</option>
{% for l in localities %}
<option value="{{ l.loc_code }}">{{ l.loc_name }}</option>
{% endfor %}

abuelitos/civilizations/templates/civilizations/options_for_localities.html
{% load i18n %}
<option value="" selected>{% translate "All Localities" %}</option>
{% for l in localities %}
<option value="{{ l.loc_code }}">{{ l.loc_name }}</option>
{% endfor %}

abuelitos/civilizations/templates/civilizations/options_for_municipalities.html
{% load i18n %}
<option value="" selected>{% translate "All Municipalities" %}</option>
{% for m in municipalities %}
<option value="{{ m.agem_code }}">{{ m.agem_name }}</option>
{% endfor %}

abuelitos/civilizations/templates/civilizations/people_base.html
{% extends "th_olian/dashboard_base.html" %}
{% load i18n static %}

{% block breadcrumbbar_list %}
<li class="breadcrumb-item"><a href="{% url "civilizations:people_search" %}">{% translate "People" %}</a></li>
{% endblock breadcrumbbar_list %}

abuelitos/civilizations/templates/civilizations/person_base.html
{% extends "th_olian/dashboard_base.html" %}
{% load i18n static %}

{% block breadcrumbbar_list %}
<li class="breadcrumb-item"><a href="{% url "civilizations:person_search" %}">{% translate "People" %}</a></li>
{% endblock breadcrumbbar_list %}

abuelitos/civilizations/templates/civilizations/person_search_form.html
{% extends "civilizations/person_base.html" %}
{% load i18n static civilizations_extras %}

{% block more_css %}
<link href="{% static "th_olian/plugins/switchery/switchery.min.css" %}" rel="stylesheet" type="text/css">
<link href="{% static "th_olian/plugins/select2/select2.min.css" %}" rel="stylesheet" type="text/css">
{% endblock more_css %}

{% block breadcrumbbar_title %}{% translate "Search People" %}{% endblock breadcrumbbar_title %}

{% block breadcrumbbar_list %}
{{ block.super }}
<li class="breadcrumb-item active" aria-current="page">{% translate "Search People" %}</li>
{% endblock breadcrumbbar_list %}

{% block contentbar_content %}
<!-- Start row -->
<div class="row">
    <!-- Start col -->
    <div class="col-lg-12">
        <div class="card m-b-30">
            <div class="card-body">
                <h5 class="card-title font-16">{% translate "Enter the information of the person and click on search!" %}</h5>
                <h6 class="card-subtitle">{% translate "You don't have to enter the person's information accurately; you can enter just a part of their name, an approximate birth year, or only the state where they lived." %}</h6>
                <form method="get" action="{% url "civilizations:person_search" %}">
                    {% if form.non_field_errors %}<div class="alert alert-danger" role="alert">{{ form.non_field_errors }}</div>{% endif %}
                    <div class="form-row">
                        <div class="form-group col-md-2">
                            <label for="{{ form.full_name_or_alias.id_for_label }}" class="sr-only">{% translate "Name Or Alias" %}</label>
                            <input type="text" class="form-control {{ form.full_name_or_alias.errors|yesno:"is-invalid," }}" placeholder="{% translate "Name Or Alias" %}" value="{{ request.GET.full_name_or_alias }}" id="{{ form.full_name_or_alias.id_for_label }}" name="{{ form.full_name_or_alias.html_name }}">
                            <div class="invalid-feedback">{% for error in form.full_name_or_alias.errors %}<li>{{ error|escape }}</li>{% endfor %}</div>
                        </div>
                        <div class="form-group col-md-1">
                            <label for="{{ form.year_of_birth.id_for_label }}" class="sr-only">{% translate "Birth Year" %}</label>
                            <input type="number" class="form-control {{ form.year_of_birth.errors|yesno:"is-invalid," }}" placeholder="{% translate "Birth Year" %}" value="{{ request.GET.year_of_birth }}" id="{{ form.year_of_birth.id_for_label }}" name="{{ form.year_of_birth.html_name }}">
                            <div class="invalid-feedback">{% for error in form.year_of_birth.errors %}<li>{{ error|escape }}</li>{% endfor %}</div>
                        </div>
                        <div class="form-group col-md-1">
                            <label for="{{ form.year_of_death.id_for_label }}" class="sr-only">{% translate "Death Year" %}</label>
                            <input type="number" class="form-control {{ form.year_of_death.errors|yesno:"is-invalid," }}" placeholder="{% translate "Death Year" %}" value="{{ request.GET.year_of_death }}" id="{{ form.year_of_death.id_for_label }}" name="{{ form.year_of_death.html_name }}">
                            <div class="invalid-feedback">{% for error in form.year_of_death.errors %}<li>{{ error|escape }}</li>{% endfor %}</div>
                        </div>
                        <div class="mx-md-auto"></div>
                        <div class="form-group col-md-1">
                            <label for="{{ form.agee_code.id_for_label }}" class="sr-only">{% translate "State" %}</label>
                            <select class="select2-single form-control {{ form.agee_code.errors|yesno:"is-invalid," }}" id="{{ form.agee_code.id_for_label }}" name="{{ form.agee_code.html_name }}" hx-get="{% url "civilizations:options_for_agem_code" %}" hx-target="#{{ form.agem_code.id_for_label }}">
                                {% for s in options_for_agee_code %}
                                {% if forloop.first %}<option value="">{% translate "All States" %}</option>{% endif %}
                                <option value="{{ s.agee_code }}" {{ s.is_selected|yesno:"selected," }}>{{ s.agee_name }}</option>
                                {% empty %}
                                <option value="" selected>{% translate "All States" %}</option>
                                {% for widget in form.agee_code.subwidgets %}{{ widget }}{% endfor %}
                                {% endfor %}
                            </select>
                            <div class="invalid-feedback">{% for error in form.agee_code.errors %}<li>{{ error|escape }}</li>{% endfor %}</div>
                        </div>
                        <div class="form-group col-md-2">
                            <label for="{{ form.agem_code.id_for_label }}" class="sr-only">{% translate "Municipality" %}</label>
                            <select class="select2-single form-control {{ form.agem_code.errors|yesno:"is-invalid," }}" id="{{ form.agem_code.id_for_label }}" name="{{ form.agem_code.html_name }}" hx-get="{% url "civilizations:options_for_loc_code" %}" hx-target="#{{ form.loc_code.id_for_label }}" hx-include="[name='{{ form.agee_code.html_name }}'], [name='{{ form.agem_code.html_name }}']">
                                {% for m in options_for_agem_code %}
                                {% if forloop.first %}<option value="">{% translate "All Municipalities" %}</option>{% endif %}
                                <option value="{{ m.agem_code }}" {{ m.is_selected|yesno:"selected," }}>{{ m.agem_name }}</option>
                                {% empty %}
                                <option value="" selected>{% translate "All Municipalities" %}</option>
                                {% endfor %}
                            </select>
                            <div class="invalid-feedback">{% for error in form.agem_code.errors %}<li>{{ error|escape }}</li>{% endfor %}</div>
                        </div>
                        <div class="form-group col-md-2">
                            <label for="{{ form.loc_code.id_for_label }}" class="sr-only">{% translate "Locality" %}</label>
                            <select class="select2-single form-control {{ form.loc_code.errors|yesno:"is-invalid," }}" id="{{ form.loc_code.id_for_label }}" name="{{ form.loc_code.html_name }}">
                                {% for l in options_for_loc_code %}
                                {% if forloop.first %}<option value="">{% translate "All Localities" %}</option>{% endif %}
                                <option value="{{ l.loc_code }}" {{ l.is_selected|yesno:"selected," }}>{{ l.loc_name }}</option>
                                {% empty %}
                                <option value="" selected>{% translate "All Localities" %}</option>
                                {% endfor %}
                            </select>
                            <div class="invalid-feedback">{% for error in form.loc_code.errors %}<li>{{ error|escape }}</li>{% endfor %}</div>
                        </div>
                        <div class="form-group col-md-2 text-right">
                            <button type="submit" class="btn btn-primary">{% translate "Search" %}</button>
                        </div>
                    </div>
                </form>
                <div class="mt-3"></div>
                <div class="table-responsive m-b-30">
                    <table class="table table-sm">
                        <thead class="thead-light">
                            <tr>
                                <th scope="col">{% translate "Full Name" %}</th>
                                <th scope="col">{% translate "Alias" %}</th>
                                <th scope="col">{% translate "Date Of Birth" %}</th>
                                <th scope="col">{% translate "Date Of Death" %}</th>
                                <th scope="col">{% translate "Father" %}</th>
                                <th scope="col">{% translate "Mother" %}</th>
                                <th scope="col">{% translate "Locality" %}</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for person in object_list %}
                            <tr>
                                <td><a href="{{ person.get_absolute_url }}">{{ person.full_name }}</a></td>
                                <td>{{ person.alias|default:"-" }}</td>
                                <td>{{ person.date_of_birth|default:"-" }}</td>
                                <td>{{ person.date_of_death|default:"-" }}</td>
                                <td>{% if person.father %}<a href="{{ person.father.get_absolute_url }}">{{ person.father.full_name }}</a>{% else %}-{% endif %}</td>
                                <td>{% if person.mother %}<a href="{{ person.mother.get_absolute_url }}">{{ person.mother.full_name }}</a>{% else %}-{% endif %}</td>
                                <td>{% if person.locality %}<a href="#">{{ person.locality }}</a>{% else %}-{% endif %}</td>
                            </tr>
                            {% empty %}
                            <tr><td colspan="7" class="text-center">{% translate "People not found!" %}</td></tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% show_pagination paginator page_obj request.GET %}
            </div>
        </div>
    </div>
    <!-- End col -->
</div>
<!-- End row -->
{% endblock contentbar_content %}

{% block more_js %}
<script src="{% static "th_olian/js/horizontal-menu.js" %}"></script>
<script src="{% static "th_olian/plugins/switchery/switchery.min.js" %}"></script>
<script src="{% static "th_olian/plugins/select2/select2.min.js" %}"></script>
<script src="{% static "th_olian/js/custom/custom-form-select.js" %}"></script>
<script src="{% static "th_olian/plugins/moment/moment.js" %}"></script>
<script src="{% static "th_olian/js/core.js" %}"></script>
<script>
    $('#{{ form.agee_code.id_for_label }}').change(function() {
        var selectLocality = $('#{{ form.loc_code.id_for_label }}')
        selectLocality.empty()
        selectLocality.append(`<option value="" selected>{% translate "All Localities" %}</option>`)
    })
</script>
{% endblock more_js %}